# Generated by Django 4.1.13 on 2024-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
